export { MineComp } from './src/main/ets/views/MineComp'

export { ClockedComp } from './src/main/ets/views/ClockedComp'

export { StudyTimeComp } from './src/main/ets/views/StudyTimeComp'

export { WordComp } from './src/main/ets/views/WordComp'

export { FackAIComp } from './src/main/ets/views/FackAIComp'
export { AboutMyComp } from './src/main/ets/views/AboutMyComp'
export { RecommendedComp } from './src/main/ets/views/RecommendedComp'
export { SettingsComp } from './src/main/ets/views/SettingsComp'

export { LoginComp } from './src/main/ets/views/LoginComp'

export { ProfileEditComp } from './src/main/ets/views/ProfileEditComp'

export { OptionalComp } from './src/main/ets/views/OptionalComp'
